
import os
import json
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

SYSTEM_PROMPT = """You are a text provenance analyst. Given a piece of text, assess the \
likelihood that it was generated by an AI language model versus written by a human.

Consider semantic coherence, phrasing patterns, stylistic uniformity, and whether the \
reasoning or narrative flow feels natural and idiosyncratic (human-like) or smooth and \
formulaic (AI-like).

Respond with ONLY a JSON object in this exact format, no other text:
{"ai_probability": <float between 0.0 and 1.0>, "reasoning": "<one short sentence>"}

ai_probability close to 1.0 means you believe the text is very likely AI-generated.
ai_probability close to 0.0 means you believe the text is very likely human-written.
"""


def get_llm_signal(text: str) -> dict:
    """
    Signal 1: LLM-based classification via Groq.

    Sends the text to the model and asks it to assess whether it reads as
    AI-generated or human-written, holistically.

    Returns a dict:
        {
            "score": float,       # 0.0 - 1.0, probability text is AI-generated
            "reasoning": str      # short explanation from the model
        }

    Blind spot: can be fooled by lightly-edited AI text or by very polished,
    formal human writing that superficially resembles AI patterns.
    """
    try:
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": text},
            ],
            temperature=0.0,
        )

        raw_output = response.choices[0].message.content.strip()
        parsed = json.loads(raw_output)

        score = float(parsed.get("ai_probability", 0.5))
        score = max(0.0, min(1.0, score))  # clamp to valid range

        return {
            "score": score,
            "reasoning": parsed.get("reasoning", "")
        }

    except (json.JSONDecodeError, KeyError, ValueError) as e:
        # If the model doesn't return valid JSON, fall back to a neutral score
        # rather than crashing the request. This is a known limitation of
        # relying on an LLM to self-report structured output.
        return {
            "score": 0.5,
            "reasoning": f"Could not parse model output: {e}"
        }


if __name__ == "__main__":
    # Quick standalone test. Run with: python signals/llm_signal.py
    test_inputs = [
        "Artificial intelligence represents a transformative paradigm shift in "
        "modern society. It is important to note that while the benefits of AI "
        "are numerous, it is equally essential to consider the ethical "
        "implications. Furthermore, stakeholders across various sectors must "
        "collaborate to ensure responsible deployment.",

        "ok so i finally tried that new ramen place downtown and honestly? "
        "underwhelming. the broth was fine but they put WAY too much sodium in "
        "it and i was thirsty for like three hours after. my friend got the "
        "spicy version and said it was better. probably won't go back unless "
        "someone drags me there",
    ]

    for i, text in enumerate(test_inputs, 1):
        result = get_llm_signal(text)
        print(f"Test input {i}:")
        print(f"  Score: {result['score']}")
        print(f"  Reasoning: {result['reasoning']}")
        print()